spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/springpostgres
    username: postgres
    password: postgres

  sql:
    init:
      mode: always

#/actuator
management:
  endpoints:
    web:
      exposure:
        include: "*"